### ISSUE TITLE
1337 khouribga

### ISSUE THREAD

**Issue by chzabakh** [pvarry/intra42#23]
there's a problem displaying students in E2 in the middle ranges.
![Screenshot_2019-10-18-12-58-05-956_com paulvarry intra42](https://user-images.githubusercontent.com/56484562/67092417-0b202800-f1a7-11e9-9db8-b4cae111bfeb.png)

**Comment by pvarry** [comment]
Hello,
I just look on the latest modification of the cluster map from public contribution and I notice the cluster "e2" from campus 16 - Khouribga. Do you think this is a mistake and should be undo ? I can also copy the cluster "e1" to have a base layout ? What do you thinks ?

**Comment by chzabakh** [comment]
actually there was an update that fixed the problem after i posted, and i thought you intentionally fixed it XD

**Comment by pvarry** [comment]
Did you know the "Contribute to Cluster Map" feature of the app ? If not a button is available on the bottom of Cluster Map view.

Actually I synchronize the map information on each release, so someone fixed it and it was published. The problem is the cluster was deleted by someone and if this change is not reverted the cluster will not be available on the next release. 

I think I will replace the map exited by the community with the currently published one, this is ok for you ?

**Comment by chzabakh** [comment]
actually i tried to contribute by creating a new entry called 16-khouribga stage2 (e2), but when i add an element to the new created map, like a computer, it disapears immediatly.
and to answer your question, e2 have the same base layout as e1.
by the way, projects feedback are not displayed anymore.

**Comment by pvarry** [comment]
I just copy e1 to e2.

For the other bugs you talking about, I take notes and I will fix then in a next release
